title: Sarah's GIS Portfolio # your name (or website title) here
logo: "/images/PicsArt_03-20-11.46.38.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Secondary Biology Teacher for Baltimore City Schools (2021 - Current)
 Former Research Assistant in the Li-Lab at the Insitute for Marine Environmental Technology (2020 - 2021)
  <br><br>
  <a href="https://www.linkedin.com/in/sarah-carpe-10a128180">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://rad-sc.github.io/CV">View My CV</a> 
show_downloads: false
google_analytics:
theme: jekyll-theme-time-machine
