title: Sarah Carpe # your name (or website title) here
logo: "/images/PicsArt_03-20-11.46.38.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 GIS Research Assistant for USDA Forest Service, Student Researcher at UMBC, Environmental Science B.S. '2020
  <br><br>
 Experienced in ArcGis and QGIS, Intermediate in R and Python. Lab management experience and facility with molecular biology techniques. 
  <br><br>
  <a href="https://www.linkedin.com/in/sarah-carpe-10a128180">View My LinkedIn Profile</a> 

show_downloads: false
google_analytics:
theme: jekyll-theme-time-machine
