title: Sarah Carpe's GIS Portfolio # your name (or website title) here
logo: "/images/PicsArt_03-20-11.46.38.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Seasonal Ranger at Patapsco Valley State Park, GIS Research Assistant for USDA Forest Service, Environmental Science B.S. '2020
  <br><br>
 Skilled in ArcGis and QGIS, intermediate in R, introductory experience in Python. Experience and proficiency with molecular biology laboratory techniques. 
  <br><br>
  <a href="https://www.linkedin.com/in/sarah-carpe-10a128180">View My LinkedIn Profile</a> 

show_downloads: false
google_analytics:
theme: jekyll-theme-time-machine
