title: Sarah's GIS Portfolio # your name (or website title) here
logo: "/images/PicsArt_03-20-11.46.38.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Seasonal Ranger at Patapsco Valley State Park, GIS Research Assistant for USDA Forest Service.
 <br><br>
 B.S. in Environmental Science and Geography '2020, University of Maryland Baltimore County.
  <br><br>
Click the links below to access my CV and my LinkedIn Profile
  <br><br>
  <a href="pdfs/CV.pdf">View My CV</a> 
  <a href="https://www.linkedin.com/in/sarah-carpe-10a128180">View My LinkedIn Profile</a> 


show_downloads: false
google_analytics:
theme: jekyll-theme-time-machine
